### ISSUE TITLE
Provide a GitHub Action

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixfmt#76]
It'd be really great if I could hook up a GitHub Action with nixfmt so it provided annotations to the code about reformatting that needs doing.

**Comment by Lucus16** [comment]
I think that would be cool too, but I don't really know anything about
Github actions. There is already the -c flag to check if files are
formatted, for use in CI. If you just want a list of files that need
formatting, it should be pretty trivial and I'd appreciate a PR. If github
supports annotations per line, I think that would be easiest to achieve
with a separate diff tool since nixfmt does not remember source locations
after parsing.

**Comment by omkumar312** [comment]
I suggest adding a GitHub Action to check Nix formatting using nixfmt and annotate issues in pull requests.
`name: Check Nix Formatting

Create a workflow:  <-add a file named->.github/workflows/nixfmt.yml

`name: Check Nix Formatting

on: [pull_request, push]

jobs:
  nixfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: nix-env -iA nixpkgs.nixfmt
      - run: nixfmt --check .
      - run: nixfmt --diff . | sed 's/^/::error file=/' || true
`
This workflow installs nixfmt, checks formatting, and uses GitHub's problem matcher to annotate any reformatting needed directly in the pull request.

**Comment by omkumar312** [comment]
I suggest adding a GitHub Action to check Nix formatting using nixfmt and annotate issues in pull requests.

Create a workflow:  <-add a file named->.github/workflows/nixfmt.yml

`name: Check Nix Formatting

on: [pull_request, push]

jobs:
  nixfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: nix-env -iA nixpkgs.nixfmt
      - run: nixfmt --check .
      - run: nixfmt --diff . | sed 's/^/::error file=/' || true`
This workflow installs nixfmt, checks formatting, and uses GitHub's problem matcher to annotate any reformatting needed directly in the pull request.

**Comment by omkumar312** [comment]
steps workflow
1. Checkout Code: Pulls the latest code from the repository.
2. Install nixfmt: Installs the nixfmt tool.
3. Check Formatting: Verifies if the Nix files are correctly formatted.
4. Annotate Issues: Adds inline annotations to the pull request for any formatting issues.

The action ensures code the highlights formatting issues directly in pull requests.

**Comment by dasJ** [comment]
I don't think this is implementable anymore with the removal of recursive mode. A GH action in treefmt would probably be more appropriate.

**Comment by infinisil** [comment]
Briefly discussed in the meeting today, agreed with @dasJ

**Comment by cdepillabout** [comment]
While I can certainly understand if the nixfmt considers this out of scope, I disagree with @dasJ:

> I don't think this is implementable anymore with the removal of recursive mode.

It is certainly still possible to implement a GitHub Action that finds all the `.nix` files in a repo, runs `nixfmt` on them, and fails if any of them are not formatted.

I'm currently in the process of switching my company over to using `nixfmt-rfc-style`, and not having an out-of-the-box, easy-to-use GitHub Action makes it just slightly harder to switch over.

**Comment by infinisil** [comment]
I'd like to reconsider this. Being able to have a simple nixfmt check with GHA would be nice. Some brainstorming on that:

Could have an interface like this:
```yml
# Put this in your repos .github/workflows/nixfmt.yml
name: "Check Nix formatting"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: NixOS/treefmt-nix-action@v1
      with:
        nixpkgs: https://github.com/NixOS/nixpkgs/archive/f1c5d6d23fd57011b78cb2424f5c73e68c9e8879.tar.gz
        treefmt-nix: https://github.com/numtide/treefmt-nix/3d0579f5cc93436052d94b73925b48973a104204.tar.gz
        module: |
          {
            # See https://github.com/numtide/treefmt-nix/tree/main/programs for more options 
            programs.nixfmt-rfc-style.enable = true;
          }
        # As an alternative to the above:
        # file: treefmt.nix
        # flake: .#treefmt
```

In the back this would:
- Create a `treefmt.nix` file like this:
  ```nix
  {
    # Alternatively, get pinned versions from npins, flakes, niv, gridlock or so
    nixpkgs ? fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/f1c5d6d23fd57011b78cb2424f5c73e68c9e8879.tar.gz";
      # sha256 = "";
    },
    treefmt-nix ? fetchTarball {
      url = "https://github.com/numtide/treefmt-nix/3d0579f5cc93436052d94b73925b48973a104204.tar.gz";
      # sha256 = "";
    },
    system ? builtins.currentSystem,
    pkgs ? import nixpkgs {
      config = { };
      overlays = [ ];
      inherit system;
    };
  }
  let
    treefmtEval = (import treefmt-nix).evalModule pkgs
      {
        # See https://github.com/numtide/treefmt-nix/tree/main/programs for more options 
        programs.nixfmt-rfc-style.enable = true;
      }
      ;
  };
  in
  {
    # Use this with `mkShell { inputsFrom = [ treefmt.shell ]; packages = [ ... ]; }
    # shell = treefmtEval.config.build.devShell;
    pkg = treefmtEval.config.build.wrapper;
  };
  ```
- Run `nix-build treefmt.nix -A pkg`
- Clone the users repo
- Run `result/bin/treefmt .` in the repo

The action should also tell the user that they can copy that generated file and put it in `treefmt.nix` to allow more reuse with other Nix code. Or alternatively use `flake.nix`.
